title: RedLua's Blog
description: Personal writing

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "sunrise"
logo: "/assets/images/favicon.png"
repository: "tarragoesteve/redlua"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist

tag_archive:
  type: liquid
  path: /tags/

show_taxonomy: true

include:
  - _pages

author:
  name: "Esteve i Laia"
  links:
    - label: "Esteve's GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tarragoesteve"
    - label: "Laia's GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/laisolizq"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tarragoesteve/redlua"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true